### ISSUE TITLE
deb: crystal package depends on crystal1.10 itself conflicting with crystal

### ISSUE THREAD

**Issue by matlag** [crystal-lang/distribution-scripts#264] opened 2023-11-10 22:18 UTC
Hello there!

Context: I have a personal server running Yunohost, on which I have the Invidious app installed. Invidious has crystal as a dependency.
Last update of Individious failed, and backup restore failed, both due to failure reinstalling `crystal`.

Yunohost is Debian based, and the installation script uses the following:

`curl -fsSL https://crystal-lang.org/install.sh | bash -s -- --channel=stable`

When checking the packages, here's what I have:

`apt show crystal`

```
Package: crystal
Version: 1.10.1-1+3.2
Priority: extra
Section: devel
Maintainer: Crystal Team <crystal@manas.tech>
Installed-Size: 57.3 kB
Depends: crystal1.10
Homepage: https://crystal-lang.org
Download-Size: 51.8 kB
APT-Sources: http://download.opensuse.org/repositories/devel:/languages:/crystal/Debian_Unstable  Packages
Description: Crystal is a general-purpose, object-oriented programming language.
 With syntax inspired by Ruby, it is a compiled language with static type-checking,
 serving both, humans and computers.
```

`apt show crystal1.10`

```
Package: crystal1.10
Version: 1.10.1-1+1.16
Priority: extra
Section: devel
Maintainer: Crystal Team <crystal@manas.tech>
Installed-Size: 133 MB
Provides: crystal
Depends: gcc, pkg-config, libpcre3-dev, libpcre2-dev, libevent-dev
Recommends: libssl-dev, libz-dev, libxml2-dev, libgmp-dev, libyaml-dev
Conflicts: crystal
Homepage: https://crystal-lang.org
Download-Size: 31.8 MB
APT-Sources: http://download.opensuse.org/repositories/devel:/languages:/crystal/Debian_Unstable  Packages
Description: Crystal is a general-purpose, object-oriented programming language.
 With syntax inspired by Ruby, it is a compiled language with static type-checking,
 serving both, humans and computers.
```

The `crystal` package depends on `crystal1.10`, but `crystal1.10` conflicts with `crystal`, 
That leaves it in a broken state.

**Comment by straight-shoota** [comment] 2023-11-10 22:59
Doh. 🤦 I'll fix this in the package definition.

As a workaround you should be able to explicitly install `crystal1.10` when passing the environment variable `CRYSTAL_VERSION=1.10` to the installer script.

**Comment by straight-shoota** [comment] 2023-11-13 13:29
It took some time for the package updates to manifest in the repositories, but it's fixed now.

**Comment by matlag** [comment] 2024-01-16 21:54
Sorry to re-open this, but we now have crystal 1.11 in the repo, and guess what issue I'm facing...

`apt show crystal`

```
Package: crystal
Version: 1.11.0-1+1.3
Priority: extra
Section: devel
Maintainer: Crystal Team <crystal@manas.tech>
Installed-Size: 7,168 B
Depends: crystal1.11
Homepage: https://crystal-lang.org
Download-Size: 1,300 B
APT-Sources: http://download.opensuse.org/repositories/devel:/languages:/crystal/Debian_Unstable  Packages
Description: Crystal is a general-purpose, object-oriented programming language.
 With syntax inspired by Ruby, it is a compiled language with static type-checking,
 serving both, humans and computers.
```

`apt show crystal1.11`

```
Package: crystal1.11
Version: 1.11.1-1+1.2
Priority: extra
Section: devel
Maintainer: Crystal Team <crystal@manas.tech>
Installed-Size: 136 MB
Provides: crystal
Depends: gcc, pkg-config, libpcre3-dev, libpcre2-dev, libevent-dev
Recommends: libssl-dev, libz-dev, libxml2-dev, libgmp-dev, libyaml-dev
Conflicts: crystal
Homepage: https://crystal-lang.org
Download-Size: 32.2 MB
APT-Sources: http://download.opensuse.org/repositories/devel:/languages:/crystal/Debian_Unstable  Packages
Description: Crystal is a general-purpose, object-oriented programming language.
 With syntax inspired by Ruby, it is a compiled language with static type-checking,
 serving both, humans and computers.
```

Since it's just a re-occurrence, I thought it was appropriate to re-open this rather than create a new ticket.

**Comment by straight-shoota** [comment] 2024-01-17 00:09
Argh, yeah I added these conflicts back in. Completely forgot about why they had been removed 🤦 

The problem is, their absence caused conflicts as well, described in https://forum.crystal-lang.org/t/linux-mint-package-install-failure-for-version-crystal1-11-1-11-0-1-1-1-amd64-deb/6301

So we'll need to find a way to address both issues.

**Comment by straight-shoota** [comment] 2024-01-17 01:36
I think I figured out a solution. The conflicts are now restricted to versions lower than the current one. https://build.opensuse.org/request/show/1139331

Technically, we should also define conflicts with higher versions, but those higher versions will have conflicts with the lower ones, so it might not be necessary?

Anyway, the packages are updated in *most* repositories and installation succeeds.
There is an issue however with `Debian_Unstable` which refuses to build. This seems to be an issue with the build system as it does not reproduce on a different runner. So I hope this will resolve itself. https://build.opensuse.org/package/live_build_log/devel:languages:crystal/crystal1.11/Debian_Unstable/x86_64

And because of this I noticed that the installer always uses the unstable repository on debian. So effectively, the installer doesn't see the new packages on any debian version, because it always wants to install from unstable 🤦
As a workaround, you can run the installer with the environment variable `DISTRO_REPO=Debian_12` (or whatever version you're using).
Or follow the manual installation instructions from OBS: https://software.opensuse.org//download.html?project=devel%3Alanguages%3Acrystal&package=crystal

**Comment by straight-shoota** [comment] 2024-01-17 16:54
The installer has been updated and it should now choose the appropriate repository for any debian version.

`Debian Unstable` still won't build, but we have to wait for build.opensuse.org to resolve this.

**Closed by straight-shoota** 2024-01-17 16:54 UTC
